Trip offer service - search & get offer
WariatInc/rsww-travel-agency-backend pull request #35
Opened 2023-05-02 13:18 UTC by Mazurel

Issue: #26 

FYI: Komenda, aby wciągnąć sobie dane z mongo: `mongorestore -d trip_offer_mongo --host=localhost --port=27017 --username=mongodb_admin --password=mongodb --authenticationDatabase="admin" FOLDER`, gdzie FOLDER jest z [link](https://drive.google.com/file/d/1i07d8anl8i4g2i2F0N-W9Roch2hL2qxW/view?usp=share_link)

2023-05-02 15:51 UTC, MD-00 requested changes
Na pierwszy rzut oka brakuje mi tu paginacji. Musimy się zastanowić, czy zrealizować ją właśnie po stronie backendu (najbardziej sensowne, ale trudniejsze w implementacji), czy frontendu (dłuższe ładowanie, ale łatwiejsze w implementacji)

2023-05-02 15:57 UTC, Mazurel commented
> Na pierwszy rzut oka brakuje mi tu paginacji. Musimy się zastanowić, czy zrealizować ją właśnie po stronie backendu (najbardziej sensowne, ale trudniejsze w implementacji), czy frontendu (dłuższe ładowanie, ale łatwiejsze w implementacji)

Na razie dałem CAP na maksymalnie 200 wyników z searcha i zakładałem, że paginację po stronie frontendu zrobimy, ale jak wolisz można też po stronie backendu, aczkolwiek tak jak mówisz trzeba by rozkminić jak to dobrze zrobić.

Ewentualnie można też zrobić, że sam search zwróci tylko listę UUID ofert, a frontend będzie pytać o szczegóły każdej z nich już przy liście ofert.

2023-05-02 15:59 UTC, xTaube commented on trip_offer_service/src/offer/api.py
> +        options = SearchOptions()
Możesz wykorzystać do tego `marshmallowa` i `webargs`, to nie będziesz musiał samemu walidować tego wszystkiego. Możesz zobaczyć przykład w `reservation_service` jak to jest zrobione

2023-05-02 16:05 UTC, xTaube commented on trip_offer_service/src/offer/domain/queries/get_offer_query.py
> +        assert result is not None
tutaj nie możemy zrobić takiego asserta, jeżeli nie ma takiego rekordu w bazie to powinniśmy zwrócić stosowną informację
```suggestion
    def get_offer(self, offer_id: UUID) -> Offer:
        result = self.client.get_db()[self.collection_name].find_one(
            {"offer_id": str(offer_id)}
        )
        if not result:
            raise OfferNotFoundException
```
I exceptiona obsłużyć w `Resource'ie` i zwróci informację do użytkonika 'offer_not_found_error'

2023-05-02 16:08 UTC, xTaube commented on trip_offer_service/src/offer/infrastructure/queries/search.py
> +    max_offers: int = 200
wydaje mi się że to nie potrzebne, powinna być paginacja tak na 25-50 rekordów

2023-05-02 16:11 UTC, xTaube commented on trip_offer_service/src/offer/infrastructure/queries/search.py
> +class SearchOptions:
Ogólnie za miast `dataclass'y` zrobiłbym schema przy użyciu 'marshmallowa', która będzie to walidować, i opcje wrzucał do query jako po prostu `**kwargs`

2023-05-02 16:18 UTC, xTaube commented
Brakuje jeszcze dodania w `make'u` komendy, która podczas inicjalizacji bazy danych wczyta nam `db_dump`

2023-05-02 18:09 UTC, MD-00 submitted a review, later dismissed
daję approve, bo wcześniej zamiast comment dałem request changes; a nie chcę blokować tego PRa

2023-05-03 17:56 UTC, Mazurel commented on trip_offer_service/src/offer/domain/queries/search_offer_query.py
> +class SearchOfferQuery(ISearchOfferQuery):
Czyli zarówno `GetOffer` jak i `SearchOffer` to powinny być twoim zdaniem viewsy ? Pozmieniać wtedy im tylko nazwy i przenieść do `infrastructure.storage.views` ? 

Niestety pierwszy raz korzystam z tego rodzaju nazewnictwa i trochę nie mam intuicji do tych nazw.

2023-05-03 18:21 UTC, xTaube commented on trip_offer_service/src/offer/api.py
> +            return jsonify(ok=False, error=f"Invalid UUID: {uuid}")
przy responsie nie musisz dodawać do payload'a `ok=False`  ani `ok=True` zamiast tego dodaj odpowiedni status code `HTTPStatus.OK` jeżeli jest wszystko dobrze lub w tym przypadku `HTTPStatus.NOT_FOUND`, możesz podpatrzeć w `reservation_service.reservation.api` jak to wygląda

2023-05-03 18:22 UTC, xTaube commented on trip_offer_service/src/offer/api.py
> +            return jsonify(ok=False, error=f"Errors: {err.messages}")
Tutaj tak samo, zamień `ok=False` na odpowiedni `status_code`

2023-05-03 18:22 UTC, xTaube commented on trip_offer_service/src/offer/domain/queries/get_offer_query.py
> +            if result is None
wystarczy samo `if result` raczej

2023-05-03 18:23 UTC, xTaube commented on trip_offer_service/src/offer/domain/queries/search_offer_query.py
> +class SearchOfferQuery(ISearchOfferQuery):
Ogólnie tak, ale myślę że żeby przyszpieszyć tego PR to zostawmy już to tak jak jest

2023-05-03 19:07 UTC, xTaube commented on trip_offer_service/src/offer/api.py
> +                HTTPStatus.BAD_REQUEST,
Powinno być `HTTPStatus.NOT_FOUND`

2023-05-03 19:07 UTC, xTaube approved these changes

2023-05-03 19:10 UTC, merged